name: Deploy Docs and Coverage

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copiar cobertura
        run: |
          mkdir -p gh-pages/cobertura
          cp -r MyMath/Cobertura/* gh-pages/cobertura/
      - name: Generar documentación
        run: |
          docfx docfx.json
          mkdir -p gh-pages/docfx
          cp -r _site/* gh-pages/docfx/
      - name: Crear página index
        run: |
          cat <<EOF > gh-pages/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Reportes del Proyecto</title>
              <style>
                  body {
                      font-family: sans-serif;
                      background: #f9fafb;
                      display: flex;
                      flex-direction: column;
                      align-items: center;
                      justify-content: center;
                      height: 100vh;
                      margin: 0;
                  }
                  h1 {
                      font-size: 2rem;
                      margin-bottom: 1rem;
                  }
                  select {
                      font-size: 1rem;
                      padding: 0.5rem 1rem;
                  }
              </style>
          </head>
          <body>
              <h1>Selecciona una vista</h1>
              <select onchange="if(this.value) window.location.href=this.value">
                  <option value="">-- Elige una opción --</option>
                  <option value="cobertura/index.html">📊 Reporte de Cobertura</option>
                  <option value="docfx/index.html">📘 Documentación Técnica (DocFX)</option>
              </select>
          </body>
          </html>
          EOF
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
