name: Actvidad - 2 | Generar Documentacion con DocFx y Publicar 
env:
  DOTNET_VERSION: '8.0' # la versi贸n de .NET
  DOTNET_VERSION_TOOL: '6.0' # la versi贸n de .NET para agregar compatibilidad con .NET 6
on: push
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configurando la versi贸n de NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Compatibilidad con .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION_TOOL }}
    - name: Actualizar DocFx y dll2mmd  
      run: |
        dotnet tool update -g docfx
        dotnet tool update -g dll2mmd

    - name: Restore & Build project
      run: |
        cd MyMath
        dotnet restore Math.Lib/Math.Lib.csproj
        dotnet build Math.Lib/Math.Lib.csproj --configuration Release
    - name: Generar diagrama de clases con dll2mmd
      run: |
        cd MyMath
        dll2mmd -f Math.Lib/bin/Release/net8.0/Math.Lib.dll -o disenio.md
    - name: Inicializar DocFX
      run: |
          cd MyMath
          docfx init -y
    - name: Limpiar el directorio docs
      run: |
          rm -rf MyMath/docs/*
    - name: Modificar archivo docfx.json
      run: |
        cd MyMath
        cat > docfx.json <<EOF
        {
          "$schema": "https://raw.githubusercontent.com/dotnet/docfx/main/schemas/docfx.schema.json",
          "metadata": [
            {
              "src": [
                {
                  "src": ".",
                  "files": [
                    "**/*.csproj"
                  ]
                }
              ],
              "dest": "docs"
            }
          ],
          "build": {
            "content": [
              {
                "files": [
                  "**/*.{md,yml}"
                ],
                "exclude": [
                  "_site/**"
                ]
              }
            ],
            "resource": [
              {
                "files": [
                  "images/**"
                ]
              }
            ],
            "output": "_site",
            "template": [
              "default",
              "modern"
            ],
            "globalMetadata": {
              "_appName": "MyMath.App",
              "_appTitle": "MyMath App",
              "_enableSearch": true,
              "pdf": true
            }
          }
        }
        EOF
    - name: Modificar archivo toc.yml
      run: |
        cd MyMath
        cat > toc.yml <<EOF
        - name: Docs
          href: docs/
        EOF
    - name: Modificar archivo index.md
      run: |
        cd MyMath
        cat > index.md <<EOF
        ---
        _layout: landing
        ---

        # This is the **HOMEPAGE**.

        ## [Diagrama de Clases](disenio.md)

        ## [Pruebas](Cobertura/SummaryGithub.md)
        EOF    
    - name: Generar documentaci贸n
      run: |
        cd MyMath
        docfx metadata docfx.json
        docfx build
    - name: Publicar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: MyMath/_site