name: Actvidad - 3 | Test unitarias y Reporte de Cobertura deployment
env:
  DOTNET_VERSION: '8.0' # la versión de .NET
on: push

jobs:
  test-and-publish-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configurando la versión de NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies & Run tests with coverage
      run: |
        cd MyMath
        dotnet restore
        dotnet test --collect:"XPlat Code Coverage"
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    - name: Generate coverage Report
      run: |
        cd MyMath
        reportgenerator "-reports:./*/*/*/coverage.cobertura.xml" "-targetdir:Cobertura" -reporttypes:HTML
    - name: Deploy coverage report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: MyMath/Cobertura
