name: Actvidad - 2 | Publicar Documentacion con DocFx
env:
  DOTNET_VERSION: '8.0' # la versi贸n de .NET
on: push
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configurando la versi贸n de NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Init DocFx
      run: dotnet tool update -g docfx

    - name: Restore & Build project
      run: |
        cd MyMath
        dotnet restore Math.Lib/Math.Lib.csproj
        dotnet build Math.Lib/Math.Lib.csproj --configuration Release

    - name: Crear carpeta docs y archivo docfx.json
      run: |
        cat > docfx.json <<EOF
        {
          "metadata": [
            {
              "src": [
                {
                  "files": ["MyMath/Math.Lib/**/*.csproj"],
                  "cwd": "."
                }
              ],
              "dest": "api"
            }
          ],
          "build": {
            "content": [
              {
                "files": ["api/**.yml", "api/index.md"]
              },
              {
                "files": ["*.md"]
              }
            ],
            "dest": "_site",
            "globalMetadata": {
              "_appTitle": "Documentaci贸n de Math.Lib"
            }
          }
        }
        EOF

    - name: Generar documentaci贸n
      run: |
        docfx docfx.json

    - name: Publicar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /_site
        destination_dir: docfx # subdirectory for the report on ghpages
        keep_files: true  # for dont cleaned any sites
