name: Actividad - 4 | Release NuGet Package
env:
  DOTNET_VERSION: '8.0' # la versión de .NET
on: push


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies && Build solution
        run: |
          cd MyMath
          dotnet restore
          dotnet build --configuration Release

      - name: Pack NuGet package
        run: dotnet pack MyMath/Math.Lib/Math.Lib.csproj --configuration Release -p:PackageVersion=2022073503
      - name: NuGet sources
        run: dotnet nuget list source
      - name: Push NuGet package to GitHub Packages
        run: |
          dotnet nuget push "**/*.nupkg" \
            --skip-duplicate \
            --source "https://nuget.pkg.github.com/${{ github.actor }}/index.json" \
            --api-key ${{ secrets.NUGET_API_KEY }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2022073503
          name: Release v2022073503
          files: "**/*.nupkg"
