name: Activdad - 4 | Release NuGet Package
env:
  DOTNET_VERSION: '8.0' # la versión de .NET
on: push


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies && Build solution
        run: |
          cd MyMath
          dotnet restore
          dotnet build --configuration Release

      - name: Pack NuGet package
        run: dotnet pack MyMath/Math.Lib/Math.Lib.csproj --configuration Release -p:PackageVersion=2022073503
      - name: Agregar fuente de NuGet para GitHub Packages
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      - name: Push to GitHub Packages
        run: dotnet nuget push "**/*.nupkg" --skip-duplicate --source "github"
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v2022073503
          name: Release v2022073503
          files: "**/*.nupkg"
